# coding: utf-8
#
{
    "name": "L.Clinic",
    'version': '1.0',
    'author': 'Bisa Indonesia',
    'category': 'Sales',
    "data": [
        'data/ir_sequence_data.xml',
        'security/ir.model.access.csv',
        'wizards/submit_poli.xml',
        'wizards/submit_kasir.xml',
        'security/group.xml',
        'view/menu.xml',
        'view/hospital.xml',
        'view/poli.xml',
        'view/product.xml',
        'view/insentif.xml',
        'view/sarana_penunjang.xml',
        'report/report.xml',
        'report/report_resep.xml',
        'report/inherit_invoice.xml',
        'report/report_lab.xml',
        'report/report_hasil_lab.xml',
        'report/inherit_stocking.xml',
        'report/inherit_PO.xml',
        'report/inherit_rfq.xml',
        'report/inherit_SO.xml',
     ],
    'depends': ['base', 'sale', 'product', 'account', 'purchase','hr','purchase_request','approvals','stock', 'operating_unit', 'report_xlsx'],
    "test": [],
    "js": [],
    "css": [],
    "qweb": [],
    "installable": True,
    "auto_install": False,
}
